### ISSUE TITLE
Does not compile against current XQilla

### ISSUE THREAD

**Issue by sanmai-NL** [rug-compling/dact#131]
1. There is a dependency on XQilla that isn't stated.
2. The XQilla 2.3.0 (as bundled with Oracle Berkeley DB XML 6.0.17) is API incompatible with [`dact`](https://github.com/rug-compling/dact/tree/1cbf34d8f928a586d183fbd82f22bf654c2261f3), because of a removed header file `xqilla/ast/XPath1Compat.hpp`. This header file is included from [`src/XPathValidator.cpp`](https://github.com/rug-compling/dact/blob/1cbf34d8f928a586d183fbd82f22bf654c2261f3/src/XPathValidator.cpp#L10). 

These dependencies are relatively mature. Are you currently planning to modernize `dact`?

**Comment by sanmai-NL** [comment]
Note, `xqilla/ast/XPath1Compat.cpp` is present in XQilla [2.2.4](http://xqilla.hg.sourceforge.net/hgweb/xqilla/xqilla/file/33b91804cb3b/src/ast).

**Comment by danieldk** [comment]
We did have DB XML 6.0.x  support in 2014, see 56d0627c0b7b20f0163b97bbc3b091488a4f8dca. The problem is that it turned out that DB XML 6.0.17/18 returns incomplete results for some XPath queries. For this reason we had to revert back to DB XML 2.5.16.

Unfortunately, Oracle does not seem to have a public bug tracker for DB XML. And when we reported bugs on their forums in the past, we never heard back anything. So, I guess that we are stuck with 2.5.16 until Oracle releases a correctly-working version.

**Comment by sanmai-NL** [comment]
That's a pity! Hard lesson..

`libalpino_corpus` [depends on Berkeley DB XML (`dbxml`) >=2.5.16](https://github.com/rug-compling/alpinocorpus/blame/c69567eea9079167632620949f4376ad5e4d1e82/README.md#L57).
Yet `dact` turns out to depend on `dbxml==2.5.16`. Do you also think this should be fixed in both `README`s to the most practical constraint `dbxml==2.5.16`?

**Comment by sanmai-NL** [comment]
Unfortunately, that old version of XQilla doesn't build on Alpine Linux 3.4.3 with GCC 5.3.0 and `musl` C standard library 1.1.14.
Again an upstream issue. But this limits the usability of `dact` packaged as a container image quite a lot.

```
Building XQilla
Making all in include
make[1]: Entering directory '/tmp/dbxml-2.5.16/xqilla/build/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/tmp/dbxml-2.5.16/xqilla/build/include'
make[1]: Entering directory '/tmp/dbxml-2.5.16/xqilla/build'
/bin/sh ./libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I.. -I./src/config -I../include/ -I/tmp/dbxml-2.5.16/xerces-c-src/src -I../src/lexer/    -D_GNU_SOURCE -D_REENTRANT  -O2 -ftemplate-depth-50  -MT ReferenceCounted.lo -MD -MP -MF .deps/ReferenceCounted.Tpo -c -o ReferenceCounted.lo `test -f 'src/framework/ReferenceCounted.cpp' || echo '../'`src/framework/ReferenceCounted.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I./src/config -I../include/ -I/tmp/dbxml-2.5.16/xerces-c-src/src -I../src/lexer/ -D_GNU_SOURCE -D_REENTRANT -O2 -ftemplate-depth-50 -MT ReferenceCounted.lo -MD -MP -MF .deps/ReferenceCounted.Tpo -c ../src/framework/ReferenceCounted.cpp  -fPIC -DPIC -o .libs/ReferenceCounted.o
In file included from ../src/framework/ReferenceCounted.cpp:24:0:
../include/xqilla/framework/XPath2MemoryManager.hpp:90:11: error: 'ptrdiff_t' does not name a type
   typedef ptrdiff_t difference_type;
           ^
Makefile:2035: recipe for target 'ReferenceCounted.lo' failed
make[1]: Leaving directory '/tmp/dbxml-2.5.16/xqilla/build'
make[1]: *** [ReferenceCounted.lo] Error 1
make: *** [all-recursive] Error 1
Makefile:4857: recipe for target 'all-recursive' failed
The command '/bin/sh -c sh -x '/tmp/build.sh'' returned a non-zero code: 2
```

**Comment by danieldk** [comment]
On Wed, Aug 24, 2016, at 17:46, Sander Maijers wrote:
> `libalpino_corpus` [depends on Berkeley DB XML (`dbxml`)
> >=2.5.16](https://github.com/rug-compling/alpinocorpus/blame/c69567eea9079167632620949f4376ad5e4d1e82/README.md#L57).
> Yet `dact` turns out to depend on `dbxml==2.5.16`. Do you also think this
> should be fixed in both `README`s to the most practical constraint
> `dbxml==2.5.16`?

Definitely! I'll change that soon!

**Comment by danieldk** [comment]
On Wed, Aug 24, 2016, at 17:51, Sander Maijers wrote:
> Again an upstream issue. But this limits the usability of `dact` packaged
> as a container image quite a lot.

Isn't one of the points of containers that you can provide the
environment necessary for a software package? Just roll a minimal Ubuntu
16.04 container that uses the Dact PPA ;).

**Comment by sanmai-NL** [comment]
Yeah, but it depends on the definition of ‘you’ and ‘necessary’.
I'll see how minimal that Ubuntu container image shall turn out. :wink:

**Comment by danieldk** [comment]
Small update: I received a patch from Oracle that solves this issue, so we'll be able to switch to version 6.1.4.
